// microfrontends/react-widget-agenda/src/components/UserAddModal.jsx
import * as React from 'react';
import {useForm} from 'react-hook-form';
import {Button, Input, Modal} from 'react-daisyui'
import {yupResolver} from '@hookform/resolvers/yup';
import * as yup from 'yup';
import {useState} from 'react';
import InputField from './ui/InputField';
import {useKeycloak} from '../auth/Keycloak';
import {postUser} from '../api/users';
import PropTypes from 'prop-types';

const schema = yup.object({
    name: yup.string().required(),
    lastname: yup.string().required(),
    phone: yup.string().required(),
    address: yup.string().required()
}).required();


const UserAddModal = ({config, handleAddToast, updateUsersTable}) => {
    const [visible, setVisible] = useState(false);
    const keycloak = useKeycloak();
    const toggleVisible = () => {
        reset();
        setVisible(!visible);
    }

    const {
        control,
        reset, handleSubmit,
        formState: {errors}
    } = useForm({
        defaultValues: {
            name: '',
            lastname: '',
            address: '',
            phone: '',
        },
        resolver: yupResolver(schema)
    });


    const onSubmit = (data) => {
        toggleVisible();
        postUser(config, keycloak.token, data).then(r => {
                if (r.responseType === 'OK') {
                    handleAddToast(`User ${r.data.id} ${r.data.name} ${r.data.lastname} added!`, 'success');
                    reset(); // reset the form after submit;
                    updateUsersTable(r.data, 'add');
                } else {
                    handleAddToast(`Add contact failed!`, 'error');
                }
            }
        );
    }
    return (
        <div className="float-right">
            <Button onClick={toggleVisible} className="mb-3 mt-3">Add User</Button>
            <Modal open={visible}>
                <Modal.Header className="font-bold">
                    Add User
                </Modal.Header>
                <Modal.Body>
                    <form onSubmit={handleSubmit(onSubmit)}>
                        <InputField name='name' label='First Name'
                                    control={control}
                                    render={({field}) => <Input {...field} />}
                                    errors={errors}/>
                        <InputField name='lastname' label='Last Name'
                                    control={control}
                                    render={({field}) => <Input {...field} />}
                                    errors={errors}/>
                        <InputField name='address' label='Address'
                                    control={control}
                                    render={({field}) => <Input {...field} />}
                                    errors={errors}/>
                        <InputField name='phone' label='Phone'
                                    control={control}
                                    render={({field}) => <Input {...field} />}
                                    errors={errors}/>
                        <Modal.Actions className='place-content-between'>
                            <div className='btn' onClick={toggleVisible}>Close</div>
                            <Button className='btn btn-primary'>Submit</Button>
                        </Modal.Actions>
                    </form>
                </Modal.Body>
            </Modal>
        </div>
    );
}

UserAddModal.propTypes = {
    config: PropTypes.any.isRequired,
    handleAddToast: PropTypes.func.isRequired,
    updateUsersTable: PropTypes.func.isRequired,
}
export default UserAddModal;

// microfrontends/vue-widget-agenda/src/components/UserAddModal.vue
<script setup>
import {ref} from "vue";
import {required} from "@vuelidate/validators";
import useVuelidate from "@vuelidate/core";

const name = ref('')
const lastname = ref('')
const address = ref('')
const phone = ref('')

const showModal = ref(false);

const emit = defineEmits(["add-user"]);

// Validation Logics
const rules = {
  name: {required},
  lastname: {required},
  address: {required},
  phone: {required}
};

const $v = useVuelidate(
    rules,
    {name, lastname, address, phone}
);

const toggleModal = () => {
  showModal.value = !showModal.value;
};

const resetForm = () => {
  $v.value.$reset();
  name.value = '';
  lastname.value = '';
  address.value = '';
  phone.value = '';
};

const handleSubmit = () => {
  let data = {
    name: name.value,
    lastname: lastname.value,
    address: address.value,
    phone: phone.value
  };
  emit('add-user', data);
  toggleModal();
  resetForm();
};

const validate = (key) => {
  $v.value[key].$dirty = true;
};

</script>
<template>
  <div class="float-right">
    <label for="my-modal" class="btn mb-3 mt-3" @click="toggleModal">Add User</label>
  </div>
  <div class="modal" :class="{'modal-open': showModal }">
    <div class="modal-box">
      <div class="w-full mb-8 text-xl font-bold">Add User</div>
      <form v-on:submit.prevent="handleSubmit">
        <div>
          <div class='form-control'>
            <label class='label'>
              <span class='label-text'>Name</span>
            </label>
            <input name="name" v-model="name" type="text" class="input input-bordered focus:outline-offset-0"
                   @blur="validate('name')">
            <div v-if="$v.name.$error">
              <label class='label text-red-500' v-for="$error in $v.name.$errors" :key="$error.$property">
                Name {{ $error.$message }}
              </label>
            </div>
          </div>
          <div class='form-control'>
            <label class='label'>
              <span class='label-text'>Last Name</span>
            </label>
            <input name="lastname"
                   v-model="lastname" type="text" class="input input-bordered focus:outline-offset-0"
                   @blur="validate('lastname')"/>
            <div v-if="$v.lastname.$error">
              <label class='label text-red-500' v-for="$error in $v.lastname.$errors" :key="$error.$property">
                Lastname {{ $error.$message }}
              </label>
            </div>
          </div>
          <div class='form-control'>
            <label class='label'>
              <span class='label-text'>Address</span>
            </label>
            <input name="address"
                   v-model="address" type="text" class="input input-bordered focus:outline-offset-0"
                   @blur="validate('address')"/>
            <div v-if="$v.address.$error">
              <label class='label text-red-500' v-for="$error in $v.address.$errors" :key="$error.$property">
                Address {{ $error.$message }}
              </label>
            </div>
          </div>
          <div class='form-control'>
            <label class='label'>
              <span class='label-text'>Phone</span>
            </label>
            <input
                name="phone"
                v-model="phone" type="text" class="input input-bordered focus:outline-offset-0"
                @blur="validate('phone')"/>
            <div v-if="$v.phone.$error">
              <label class='label text-red-500' v-for="$error in $v.phone.$errors" :key="$error.$property">
                Phone {{ $error.$message }}
              </label>
            </div>
          </div>
        </div>
        <div class='"modal-action w-full place-content-between pt-3'>
          <label for="my-modal" class="btn" @click="toggleModal">Cancel</label>
          <button class="btn btn-primary float-right" :disabled="$v.$invalid">Submit</button>
        </div>
      </form>
    </div>
  </div>
</template>
