// microfrontends/react-widget-agenda/src/components/ui/Notifications.jsx
import PropTypes from 'prop-types';
import {Toast} from 'react-daisyui';
import NotificationSuccess from './NotificationSuccess';
import NotificationError from './NotificationError';

const Notifications = ({alerts, handleRemoveToast}) => {
    return <Toast>
        {alerts.map((alert, index) => (
            alert.status === 'error' ?
                <NotificationError key={alert.id} alert={alert} onClick={() => handleRemoveToast(index)}/>
                :
                <NotificationSuccess key={alert.id} alert={alert} onClick={() => handleRemoveToast(index)}/>
        ))}
    </Toast>
}

Notifications.propTypes = {
    alerts: PropTypes.arrayOf(
        PropTypes.shape({
                id: PropTypes.number.isRequired,
                text: PropTypes.string.isRequired,
                status: PropTypes.string.isRequired,
            }
        )),
    handleRemoveToast: PropTypes.func.isRequired,
}

export default Notifications;

// microfrontends/vue-widget-agenda/src/components/ui/Notifications.vue
<script setup>
import NotificationError from "./NotificationError.vue";
import NotificationSuccess from "./NotificationSuccess.vue";

const emit = defineEmits(["delete-notification"]);

defineProps({
  alerts: Object({
    id: Number,
    text: String,
    status: String
  })
});

const deleteNotification = id => {
  emit('delete-notification', id)
};
</script>

<template>
  <div class="toast toast-end">
    <div v-for="alert in alerts">
      <NotificationError v-if="alert.status==='error'" :id="alert.id" :text="alert.text" @delete-notification="deleteNotification(alert.id)"></NotificationError>
      <NotificationSuccess v-else :text="alert.text" :id="alert.id" @delete-notification="deleteNotification(alert.id)"></NotificationSuccess>
    </div>
  </div>
</template>
