// microfrontends/vue-widget-agenda/src/components/DeleteUserModal.vue
<script setup>

const emit = defineEmits(["delete-user", "cancel-delete-user"]);

const props = defineProps({
  userId: Number,
  showModal: Boolean
});

function confirmDeleteUser() {
  emit("delete-user", props.userId);
}

</script>

<template>
  <div class="modal" :class="{'modal-open': showModal }">
    <div class="modal-box">
      <h3 class="font-bold text-lg">Delete User {{ userId }}</h3>
      <div class='w-full place-content-between'>
        <div class="modal-action w-full place-content-between pt-3tion">
          <label for="my-modal" class="btn" @click="emit('cancel-delete-user')">Cancel</label>
          <button class="btn btn-primary float-right" @click="confirmDeleteUser">Confirm</button>
        </div>
      </div>
    </div>
  </div>
</template>

// microfrontends/react-widget-agenda/src/components/DeleteUserModal.jsx
import * as React from 'react';
import PropTypes from 'prop-types';
import {Button, Modal} from 'react-daisyui'


const DeleteUserModal = ({visible, toggleVisible, userId, handleConfirmDelete}) => {
    return (
        <Modal open={visible}>
            <Modal.Header className="font-bold">
                Do you want to delete the user {userId}?
            </Modal.Header>
            <Modal.Body>
                <Modal.Actions className="place-content-between">
                    <div className='btn btn-secondary' onClick={toggleVisible}>Cancel</div>
                    <Button className='btn btn-primary'onClick={handleConfirmDelete}>Confirm</Button>
                </Modal.Actions>
            </Modal.Body>
        </Modal>
    );
}

DeleteUserModal.propTypes = {
    visible: PropTypes.bool.isRequired,
    toggleVisible: PropTypes.func.isRequired,
    userId: PropTypes.number.isRequired,
    handleConfirmDelete: PropTypes.func.isRequired
}

export default DeleteUserModal;
